Can't compile rpcd. Missing crypt library.
in function `rpc_login_test_password':
/usr/src/debug/rpcd/git-r0/git/session.c:823: undefined reference to `crypt'